language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs"

notifications:
  email:
    jrgm@mozilla.com

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs"
  fast_finish: true

